version: '3'
services:
  app:
    build: .
    image: canvas_image
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "80:3000"
    container_name: canvas
    command: ['npm','start']